### ISSUE TITLE
Sticky element disappears when it becomes stuck (Solved)

### ISSUE THREAD

**Issue by japick** [leafo/sticky-kit#244]
Just a quick heads-up for anyone who has had this issue.

In my case, this was caused by the parent element having a CSS transform property set on it. Once this was removed, all worked fine.

**Comment by carasmo** [comment]
Please close this.

**Comment by japick** [comment]
@carasmo For what reason?

**Comment by carasmo** [comment]
Because it was solved. This helps others when searching.

**Comment by techyogi7** [comment]
Same issue for me too, As i don't have any CSS transform property set to the parent element.

But I can see it's not disappear but goes all the way to top main container, and that's the reason it feels like disappeared.

That would be great if someone can help with that.

**Comment by Dihgg** [comment]
@techyogi7 this is happening to me too

**Comment by gzmichael84** [comment]
Same here. No disappear but goes top. any solution?

**Comment by Namstel** [comment]
Still encountering this issue. Parent element does **not** have the _transform_ property attached to it.

EDIT:
I found this issue with a possible solution:
https://github.com/leafo/sticky-kit/issues/169

My sticky element has the .stickyme class.

So I added some CSS:
`.stickyme {
   position: static;
}`
